# Generated by Django 5.2.3 on 2025-06-12 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Feedback",
            new_name="Comment",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="message",
            new_name="text",
        ),
    ]
