# Generated by Django 5.2.3 on 2025-06-12 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_feedback_comment_rename_message_comment_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="page_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
